//! Documentation generation logic

use anyhow::Result;
use chrono::Local;
use std::path::Path;

/// Generates comprehensive AI agent documentation for a target project
pub fn generate_documentation(target_path: &Path, verbose: bool) -> Result<String> {
    let name = target_path
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("Unknown");
    let ts = Local::now().format("%Y-%m-%d %H:%M:%S");
    let notes = generate_project_notes(target_path, verbose)?;
    let sections = [
        template_guidelines::process_guidelines(),
        template_guidelines::quality_standards(),
        template_guidelines::continuous_improvement(),
        template_guidelines::code_metrics(),
        template_notes::playwright_mcp_setup(),
        notes.as_deref().unwrap_or(""),
        template_guidelines::summary(),
    ];
    Ok(format!(
        "<!-- Generated by Proact for: {name} at: {ts} -->\n{}",
        sections.join("\n")
    ))
}

/// Generates project-specific notes based on detected project type
fn generate_project_notes(path: &Path, verbose: bool) -> Result<Option<String>> {
    let types = [
        ("Cargo.toml", None, "rust"),
        ("package.json", None, "javascript"),
        ("pyproject.toml", Some("requirements.txt"), "python"),
    ];
    let notes: Vec<_> = types
        .iter()
        .filter(|(f, alt, _)| path.join(f).exists() || alt.is_some_and(|a| path.join(a).exists()))
        .map(|(_, _, kind)| {
            if verbose {
                eprintln!("  Detected {kind} project");
            }
            template_notes::project_notes(kind)
        })
        .collect();
    Ok(if notes.is_empty() {
        None
    } else {
        Some(format!(
            "## Project-Specific Guidelines\n\n{}\n\n---\n",
            notes.join("\n")
        ))
    })
}
