use clap::Parser;
use std::path::PathBuf;

const LONG_ABOUT: &str = "\
Proact generates comprehensive documentation that instructs AI coding agents \
to follow best practices, apply continuous improvement, and use tools like \
Playwright MCP for browser automation.

AI CODING AGENT NOTES:
When working with projects generated by Proact, you should:
  1. Read the generated docs/ai_agent_instructions.md for project guidelines
  2. Follow the checkpoint process described in the documentation
  3. Update docs/learnings.md when encountering issues
  4. Run proact again if project structure changes significantly

For CLI projects generated with this pattern:
  - Use -V to see copyright, license, and repository information
  - Use --help (not -h) to see extended AI agent guidance
  - Follow the generated process.md for development workflow
";

/// CLI for generating AI coding agent documentation
///
/// This module handles command-line argument parsing for the Proact tool,
/// which generates comprehensive documentation for AI coding agents.
#[derive(Parser, Debug)]
#[command(
    name = "proact",
    about = "Generate documentation for AI coding agents",
    long_about = LONG_ABOUT,
    version,
    author
)]
pub struct Args {
    /// Path to the target project directory
    ///
    /// This should be an existing directory where the AI agent documentation
    /// will be tailored for. The path can be absolute or relative.
    #[arg(value_name = "TARGET", help = "Path to an existing project directory")]
    pub target: PathBuf,

    /// Enable verbose output
    ///
    /// When enabled, provides detailed information about the generation process,
    /// including what content is being included and where files are being written.
    #[arg(short = 'v', long = "verbose", help = "Enable verbose output")]
    pub verbose: bool,

    /// Output directory for generated documentation
    ///
    /// The directory where the AI agent documentation will be written.
    /// Will be created if it doesn't exist.
    #[arg(
        short = 'o',
        long = "output-dir",
        value_name = "DIR",
        default_value = "docs",
        help = "Output directory for generated documentation"
    )]
    pub output_dir: PathBuf,

    /// Perform a dry run without creating files
    ///
    /// Shows all operations that would be performed without actually
    /// executing them. Implies verbose mode.
    #[arg(
        short = 'n',
        long = "dry-run",
        help = "Show what would be done without actually doing it"
    )]
    pub dry_run: bool,
}
