//! Documentation generator for AI coding agents

use anyhow::Result;
use chrono::Local;
use std::fs;
use std::path::Path;

use crate::metadata::{self, ProjectMetadata};
use crate::templates;

/// Generates comprehensive AI agent documentation for a target project
pub fn generate_documentation(target_path: &Path, verbose: bool) -> Result<String> {
    let project_name = target_path
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("Unknown");
    let timestamp = Local::now().format("%Y-%m-%d %H:%M:%S");

    let mut doc = format!("<!-- Generated by Proact for: {project_name} at: {timestamp} -->\n");

    doc.push_str(templates::process_guidelines());
    doc.push('\n');
    doc.push_str(templates::quality_standards());
    doc.push('\n');
    doc.push_str(templates::continuous_improvement());
    doc.push('\n');
    doc.push_str(templates::playwright_mcp_setup());
    doc.push('\n');

    if let Some(notes) = generate_project_notes(target_path, verbose)? {
        doc.push_str(&notes);
        doc.push('\n');
    }

    doc.push_str(templates::summary());
    Ok(doc)
}

/// Generates project-specific notes based on detected project type
fn generate_project_notes(target_path: &Path, verbose: bool) -> Result<Option<String>> {
    let mut notes = Vec::new();

    for (file, alt, kind) in [
        ("Cargo.toml", None, "rust"),
        ("package.json", None, "javascript"),
        ("pyproject.toml", Some("requirements.txt"), "python"),
    ] {
        let exists =
            target_path.join(file).exists() || alt.is_some_and(|f| target_path.join(f).exists());
        if exists {
            if verbose {
                eprintln!("  Detected {kind} project");
            }
            notes.push(templates::project_notes(kind));
        }
    }

    if notes.is_empty() {
        Ok(None)
    } else {
        Ok(Some(format!(
            "## Project-Specific Guidelines\n\n{}\n\n---\n",
            notes.join("\n")
        )))
    }
}

// Embed template files at compile time
const PROCESS_MD: &str = include_str!("../templates/process.md");
const TOOLS_MD: &str = include_str!("../templates/tools.md");

/// Copy or append template files to output directory
pub fn copy_templates(output_dir: &Path, verbose: bool, dry_run: bool) -> Result<()> {
    for (content, name) in [(PROCESS_MD, "process.md"), (TOOLS_MD, "tools.md")] {
        let dest = output_dir.join(name);
        let text = if dest.exists() {
            let existing = fs::read_to_string(&dest)?;
            let sep = format!(
                "\n\n---\n\n**Added by Proact on {}**\n\n",
                Local::now().format("%Y-%m-%d %H:%M:%S")
            );
            if verbose {
                eprintln!("append {}", dest.display());
            }
            format!("{existing}{sep}{content}")
        } else {
            if verbose {
                eprintln!("write {}", dest.display());
            }
            content.to_string()
        };
        if !dry_run {
            fs::write(dest, text)?;
        }
    }
    Ok(())
}

/// Generate COPYRIGHT and LICENSE files
pub fn generate_legal_files(
    target: &Path,
    _out: &Path,
    verbose: bool,
    dry_run: bool,
) -> Result<()> {
    let meta = ProjectMetadata::extract(target)?;

    let copyright = meta.copyright_string();
    let copyright_path = target.join("COPYRIGHT");
    if verbose {
        eprintln!("write {}", copyright_path.display());
    }
    if !dry_run {
        fs::write(copyright_path, copyright)?;
    }

    if meta.license == "MIT" || meta.license == "<license>" {
        let license = metadata::generate_mit_license(&meta);
        let license_path = target.join("LICENSE");
        if verbose {
            eprintln!("write {}", license_path.display());
        }
        if !dry_run {
            fs::write(license_path, license)?;
        }
    }

    Ok(())
}
